s=set()
n=int(input("enter a digit: "))
s.add(n)
n=int(input("enter a digit: "))
s.add(n)
n=int(input("enter a digit: "))
s.add(n)
n=int(input("enter a digit: "))
s.add(n)
n=int(input("enter a digit: "))
s.add(n)
n=int(input("enter a digit: "))
s.add(n)
n=int(input("enter a digit: "))
s.add(n)
n=int(input("enter a digit: "))
s.add(n)
print(s)